### ISSUE TITLE
crash on startup on grapheneos

### ISSUE THREAD

**Issue by emdete** [love2d/love-android#261]
with and without a content in /sdcard/lovegame the app crashes. a message is displayed:

```
type: crash
osVersion: google/bluejay/bluejay:14/UQ1A.231205.015/2023120800:user/release-keys
package: org.love2d.android:28
process: org.love2d.android
processUptime: 0 + 0 ms
installer: com.android.packageinstaller
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000521d2912b381
backtrace: #00 pc 00000000004eb608 /data/app/~~j2K77F0uMKjkqVo7qw4ElA==/org.love2d.android-XqhNLd-FEKBsO5B75whpTw==/lib/arm64/liblove.so (lua_pushcclosure+52) (BuildId:8fe929c600ae93db0f8a7c4f37948f2b49f05af9)

```
logcat shows(between many more lines):

````
12-11 19:35:05.080  4312  4312 D GameActivity: started
12-11 19:35:05.084  4312  4312 D GameActivity: new gamePath: 
12-11 19:35:05.084  4312  4312 V SDL     : Device: bluejay
12-11 19:35:05.084  4312  4312 V SDL     : Model: Pixel 6a
12-11 19:35:05.084  4312  4312 V SDL     : onCreate()
12-11 19:35:05.114  4312  4312 V SDL     : nativeSetupJNI()
12-11 19:35:05.114  4312  4312 V SDL     : AUDIO nativeSetupJNI()
12-11 19:35:05.115  4312  4312 V SDL     : CONTROLLER nativeSetupJNI()
12-11 19:35:05.120  1405  2200 D CompatibilityChangeReporter: Compat change id reported: 161145287; UID 10184; state: DISABLED
12-11 19:35:05.121  4312  4312 D hidapi  : Initializing Bluetooth
12-11 19:35:05.121  4312  4312 D hidapi  : Couldn't initialize Bluetooth, missing android.permission.BLUETOOTH
12-11 19:35:05.133  4312  4312 V SDL     : onStart()
12-11 19:35:05.133  4312  4312 V SDL     : onResume()
12-11 19:35:05.138  4312  4312 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10184; state: DISABLED
12-11 19:35:05.138  4312  4312 W libc    : Access denied finding property "ro.debuggable"
12-11 19:35:05.133  4312  4312 W SDLActivity: type=1400 audit(0.0:11703): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=401 scontext=u:r:untrusted_app_27:s0:c184,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=org.love2d.android
12-11 19:35:05.144  1405  2200 W WindowManager: Failed looking up window session=Session{a73eb2d 4312:u0a10184} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:6011 com.android.server.wm.Session.updateRequestedVisibleTypes:695 android.view.IWindowSession$Stub.onTransact:1034 
12-11 19:35:05.159  1405  1450 D CoreBackPreview: Window{bbb48ae u0 org.love2d.android/org.love2d.android.GameActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@78191dc, mPriority=0, mIsAnimationCallback=false}
12-11 19:35:05.165  4312  4312 V SDL     : surfaceCreated()
12-11 19:35:05.166  4312  4312 V SDL     : surfaceChanged()
12-11 19:35:05.166  4312  4312 V SDL     : pixel format RGB_565
12-11 19:35:05.166  4312  4312 V SDL     : Window size: 2142x1006
12-11 19:35:05.166  4312  4312 V SDL     : Device size: 2400x1080
12-11 19:35:05.168  1043  1683 D usf_sensor_hal: accelerometer: Enter Batch. period = 20000000, latency = 0.
12-11 19:35:05.168  1287  1287 D AOC     : A3:MSG: usf_sensor.cc, 2052: USF: Received reconfig sampling request for LSM6DSR Accelerometer.
12-11 19:35:05.169  1287  1287 D AOC     : A3:MSG: lsm6dsr_device.cc, 763: USF: Lsm6dsrDevice: Sensor 0: Enabled 1, odr_index 3.
12-11 19:35:05.169  1287  1287 D AOC     : A3:MSG: lsm6dsr_fifo.cc, 750: USF: Lsm6dsrFifo: ODR: XL/G/T/TS: 52/52/13/6 WM: 2 Intr: 52.
12-11 19:35:05.170  1287  1287 D AOC     : A3:MSG: lsm6dsr_device.cc, 671: USF: Lsm6dsrDevice: Fifo was disabled for 343750ns.
12-11 19:35:05.170  1043  1683 D usf_sensor_hal: IMU temperature: Enter Batch. period = 615385000, latency = 0.
12-11 19:35:05.171  1287  1287 D AOC     : A3:MSG: usf_sensor.cc, 2052: USF: Received reconfig sampling request for LSM6DSR Temperature.
12-11 19:35:05.172  1043  1683 D usf_sensor_hal: accelerometer: Enter Flush
12-11 19:35:05.173  4312  4451 V SDL     : Running main function SDL_main from library liblove.so
12-11 19:35:05.173  4312  4451 V SDL     : nativeRunMain()
12-11 19:35:05.175  4312  4451 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4cc1f3c1d381 in tid 4451 (SDLThread), pid 4312 (SDLActivity)
12-11 19:35:05.186   639   639 I hwservicemanager: getTransport: Cannot find entry android.hardware.graphics.allocator@4.0::IAllocator/default in either framework or device VINTF manifest.
12-11 19:35:05.187   732   732 W gralloc4: Unable to set buffer name VRI[GameActivity]#0(BLAST Consumer)0: File name too long
12-11 19:35:05.189  4312  4360 E cutils-trace: Error opening trace file: No such file or directory (2)
12-11 19:35:05.200  4455  4455 E cutils-trace: Error opening trace file: No such file or directory (2)
12-11 19:35:05.218  4456  4456 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstoneProto
12-11 19:35:05.221   833   833 I tombstoned: received crash request for pid 4451
12-11 19:35:05.222  4456  4456 I crash_dump64: performing dump of process 4312 (target tid = 4451)
12-11 19:35:05.266  4456  4456 E cutils-trace: Error opening trace file: No such file or directory (2)
12-11 19:35:05.270  1405  1635 I ActivityTaskManager: Displayed org.love2d.android/.GameActivity for user 0: +551ms
12-11 19:35:05.276  4312  4312 V SDL     : onWindowFocusChanged(): true
12-11 19:35:05.281  2061  2142 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@3a991c8
12-11 19:35:05.282  1405 10987 D CompatibilityChangeReporter: Compat change id reported: 214016041; UID 10184; state: DISABLED
12-11 19:35:05.282  1405 10987 I ImeTracker: org.love2d.android:543bef09: onRequestHide at ORIGIN_SERVER_HIDE_INPUT reason HIDE_UNSPECIFIED_WINDOW
12-11 19:35:05.282  1405 10987 I ImeTracker: org.love2d.android:543bef09: onCancelled at PHASE_SERVER_SHOULD_HIDE
12-11 19:35:05.282  1405 18632 W InputManager-JNI: Input channel object '87226aa Splash Screen org.love2d.android (client)' was disposed without first being removed with the input manager!
12-11 19:35:05.286  1405  2200 D CoreBackPreview: Window{87226aa u0 Splash Screen org.love2d.android EXITING}: Setting back callback null
12-11 19:35:05.429  4456  4456 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-11 19:35:05.429  4456  4456 F DEBUG   : Build fingerprint: 'google/bluejay/bluejay:14/UQ1A.231205.015/2023120800:user/release-keys'
12-11 19:35:05.429  4456  4456 F DEBUG   : Revision: 'MP1.0'
12-11 19:35:05.429  4456  4456 F DEBUG   : ABI: 'arm64'
12-11 19:35:05.429  4456  4456 F DEBUG   : Timestamp: 2023-12-11 19:35:05.229913569+0100
12-11 19:35:05.429  4456  4456 F DEBUG   : Process uptime: 2s
12-11 19:35:05.429  4456  4456 F DEBUG   : Cmdline: org.love2d.android
12-11 19:35:05.429  4456  4456 F DEBUG   : pid: 4312, tid: 4451, name: SDLThread  >>> org.love2d.android <<<
12-11 19:35:05.429  4456  4456 F DEBUG   : uid: 10184
12-11 19:35:05.429  4456  4456 F DEBUG   : tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
12-11 19:35:05.429  4456  4456 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x00004cc1f3c1d381
12-11 19:35:05.429  4456  4456 F DEBUG   :     x0  00004cc1f3c1d378  x1  00000000000084b8  x2  0000000000000000  x3  000000000000212e
12-11 19:35:05.429  4456  4456 F DEBUG   :     x4  0000c98ae89810b9  x5  0000ccc1f3c1f6c1  x6  0000000000000000  x7  7f7f7f7f7f7f7f7f
12-11 19:35:05.429  4456  4456 F DEBUG   :     x8  0101010101010101  x9  0000000000000000  x10 0000000000000072  x11 000000000001fe00
12-11 19:35:05.429  4456  4456 F DEBUG   :     x12 00000000000027ea  x13 0000000000000000  x14 0000000000000001  x15 000004b0e6943e99
12-11 19:35:05.429  4456  4456 F DEBUG   :     x16 0000c98ae8a5ff58  x17 0000c98ae87e35d4  x18 0000c98ae373a000  x19 0000ccc1f3c1d378
12-11 19:35:05.429  4456  4456 F DEBUG   :     x20 0000c98ae87ec2a8  x21 0000c98ae8a55a50  x22 0000c98ae889a2a6  x23 0000ccc1f3c1d378
12-11 19:35:05.429  4456  4456 F DEBUG   :     x24 0000c98ae990fbd8  x25 0000c98ae889a27e  x26 0000000000000001  x27 0000c98ae990fbdc
12-11 19:35:05.429  4456  4456 F DEBUG   :     x28 0000c98ae889a299  x29 0000c98ae990fa50
12-11 19:35:05.429  4456  4456 F DEBUG   :     lr  0000c98ae87f41c8  sp  0000c98ae990f9b0  pc  0000c98ae87e3608  pst 0000000080001000
12-11 19:35:05.429  4456  4456 F DEBUG   : 1 total frames
12-11 19:35:05.429  4456  4456 F DEBUG   : backtrace:
12-11 19:35:05.429  4456  4456 F DEBUG   :       #00 pc 00000000004eb608  /data/app/~~j2K77F0uMKjkqVo7qw4ElA==/org.love2d.android-XqhNLd-FEKBsO5B75whpTw==/lib/arm64/liblove.so (lua_pushcclosure+52) (BuildId: 8fe929c600ae93db0f8a7c4f37948f2b49f05af9)

```

**Comment by MikuAuahDark** [comment]
The backtrace looks incomplete. Is that the only backtraces that's reported?

**Comment by emdete** [comment]
yes. that is all. i did another one with some more lines (related or not):

```
12-18 14:44:31.575  1458 15851 W Binder  : Caught a RuntimeException from the binder stub implementation.
12-18 14:44:31.575  1458 15851 W Binder  : java.lang.IllegalArgumentException: Unable to get package app.vanadium.trichromelibrary_599311132
12-18 14:44:31.575  1458 15851 W Binder  : 	at com.android.server.art.Utils.getPackageOrThrow(Utils.java:271)
12-18 14:44:31.575  1458 15851 W Binder  : 	at com.android.server.art.DexUseManagerLocal.isOwningPackageForPrimaryDex(DexUseManagerLocal.java:443)
12-18 14:44:31.575  1458 15851 W Binder  : 	at com.android.server.art.DexUseManagerLocal.lambda$notifyDexContainersLoaded$9(DexUseManagerLocal.java:396)
12-18 14:44:31.575  1458 15851 W Binder  : 	at com.android.server.art.DexUseManagerLocal.$r8$lambda$hXjaMQ6JLgVjiJmhGgjNj0X7opA(DexUseManagerLocal.java:0)
12-18 14:44:31.575  1458 15851 W Binder  : 	at com.android.server.art.DexUseManagerLocal$$ExternalSyntheticLambda9.apply(R8$$SyntheticClass:0)
12-18 14:44:31.575  1458 15851 W Binder  : 	at com.android.server.art.DexUseManagerLocal.findOwningPackage(DexUseManagerLocal.java:433)
12-18 14:44:31.575  1458 15851 W Binder  : 	at com.android.server.art.DexUseManagerLocal.notifyDexContainersLoaded(DexUseManagerLocal.java:395)
12-18 14:44:31.575  1458 15851 W Binder  : 	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.notifyDexLoad(PackageManagerService.java:5577)
12-18 14:44:31.575  1458 15851 W Binder  : 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3337)
12-18 14:44:31.575  1458 15851 W Binder  : 	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6398)
12-18 14:44:31.575  1458 15851 W Binder  : 	at android.os.Binder.execTransactInternal(Binder.java:1366)
12-18 14:44:31.575  1458 15851 W Binder  : 	at android.os.Binder.execTransact(Binder.java:1302)
12-18 14:44:31.575 12263 12263 D nativeloader: InitVendorPublicLibraries: libOpenCL.so:libOpenCL-pixel.so:libedgetpu_client.google.so:libedgetpu_util.so:lib_aion_buffer.so:libmetrics_logger.so
12-18 14:44:31.575 12263 12263 D nativeloader: InitProductPublicLibraries: 
12-18 14:44:31.586 12263 12263 D nativeloader: Configuring clns-2 for other apk /data/app/~~j2K77F0uMKjkqVo7qw4ElA==/org.love2d.android-XqhNLd-FEKBsO5B75whpTw==/base.apk. target_sdk_version=28, uses_libraries=, library_path=/data/app/~~j2K77F0uMKjkqVo7qw4ElA==/org.love2d.android-XqhNLd-FEKBsO5B75whpTw==/lib/arm64:/data/app/~~j2K77F0uMKjkqVo7qw4ElA==/org.love2d.android-XqhNLd-FEKBsO5B75whpTw==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/org.love2d.android
12-18 14:44:31.586 12263 12263 D nativeloader: Extending system_exposed_libraries: libedgetpu_dba.google.so
12-18 14:44:31.596 12263 12263 V GraphicsEnvironment: Currently set values for:
12-18 14:44:31.596 12263 12263 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[]
12-18 14:44:31.596 12263 12263 V GraphicsEnvironment:   angle_gl_driver_selection_values=[]
12-18 14:44:31.596 12263 12263 V GraphicsEnvironment: ANGLE GameManagerService for org.love2d.android: false
12-18 14:44:31.596 12263 12263 V GraphicsEnvironment: org.love2d.android is not listed in per-application setting
12-18 14:44:31.596 12263 12263 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
12-18 14:44:31.604 12263 12294 I DMABUFHEAPS: Using DMA-BUF heap named: vframe-secure
12-18 14:44:31.610 12263 12263 D GameActivity: started
12-18 14:44:31.613 12263 12263 D GameActivity: new gamePath: 
12-18 14:44:31.613 12263 12263 V SDL     : Device: bluejay
12-18 14:44:31.613 12263 12263 V SDL     : Model: Pixel 6a
12-18 14:44:31.613 12263 12263 V SDL     : onCreate()
12-18 14:44:31.643 12263 12263 V SDL     : nativeSetupJNI()
12-18 14:44:31.644 12263 12263 V SDL     : AUDIO nativeSetupJNI()
12-18 14:44:31.644 12263 12263 V SDL     : CONTROLLER nativeSetupJNI()
12-18 14:44:31.648  1458 27079 D CompatibilityChangeReporter: Compat change id reported: 161145287; UID 10184; state: DISABLED
12-18 14:44:31.649 12263 12263 D hidapi  : Initializing Bluetooth
12-18 14:44:31.649 12263 12263 D hidapi  : Couldn't initialize Bluetooth, missing android.permission.BLUETOOTH
12-18 14:44:31.660 12263 12263 V SDL     : onStart()
12-18 14:44:31.661 12263 12263 V SDL     : onResume()
12-18 14:44:31.663 12263 12263 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10184; state: DISABLED
12-18 14:44:31.663 12263 12263 W libc    : Access denied finding property "ro.debuggable"
12-18 14:44:31.656 12263 12263 W SDLActivity: type=1400 audit(0.0:39142): avc:  denied  { read } for  name="u:object_r:userdebug_or_eng_prop:s0" dev="tmpfs" ino=401 scontext=u:r:untrusted_app_27:s0:c184,c256,c512,c768 tcontext=u:object_r:userdebug_or_eng_prop:s0 tclass=file permissive=0 app=org.love2d.android
12-18 14:44:31.666  1458  9787 W WindowManager: Failed looking up window session=Session{d318768 12263:u0a10184} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:6011 com.android.server.wm.Session.updateRequestedVisibleTypes:695 android.view.IWindowSession$Stub.onTransact:1034 
12-18 14:44:31.682  1458 15851 D CoreBackPreview: Window{8414467 u0 org.love2d.android/org.love2d.android.GameActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@13c003, mPriority=0, mIsAnimationCallback=false}
12-18 14:44:31.688 12263 12263 V SDL     : surfaceCreated()
12-18 14:44:31.688 12263 12263 V SDL     : surfaceChanged()
12-18 14:44:31.688 12263 12263 V SDL     : pixel format RGB_565
12-18 14:44:31.688 12263 12263 V SDL     : Window size: 2142x1006
12-18 14:44:31.688 12263 12263 V SDL     : Device size: 2400x1080
12-18 14:44:31.692  1060  1060 D usf_sensor_hal: accelerometer: Enter Batch. period = 20000000, latency = 0.
12-18 14:44:31.699  1281  1281 D AOC     : A3:MSG: usf_sensor.cc, 2052: USF: Received reconfig sampling request for LSM6DSR Accelerometer.
12-18 14:44:31.699  1281  1281 D AOC     : A3:MSG: lsm6dsr_device.cc, 763: USF: Lsm6dsrDevice: Sensor 0: Enabled 1, odr_index 3.
12-18 14:44:31.699  1281  1281 D AOC     : A3:MSG: lsm6dsr_fifo.cc, 750: USF: Lsm6dsrFifo: ODR: XL/G/T/TS: 52/52/13/6 WM: 2 Intr: 52.
12-18 14:44:31.699  1281  1281 D AOC     : A3:MSG: lsm6dsr_device.cc, 671: USF: Lsm6dsrDevice: Fifo was disabled for 348145ns.
12-18 14:44:31.700  1060  1060 D usf_sensor_hal: IMU temperature: Enter Batch. period = 615385000, latency = 0.
12-18 14:44:31.700  1281  1281 D AOC     : A3:MSG: usf_sensor.cc, 2052: USF: Received reconfig sampling request for LSM6DSR Temperature.
12-18 14:44:31.701  1060  1060 D usf_sensor_hal: accelerometer: Enter Flush
12-18 14:44:31.702 12263 12313 V SDL     : Running main function SDL_main from library liblove.so
12-18 14:44:31.702 12263 12313 V SDL     : nativeRunMain()
12-18 14:44:31.703 12263 12313 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x5a7034f84381 in tid 12313 (SDLThread), pid 12263 (SDLActivity)
12-18 14:44:31.717   641   641 I hwservicemanager: getTransport: Cannot find entry android.hardware.graphics.allocator@4.0::IAllocator/default in either framework or device VINTF manifest.
12-18 14:44:31.718   733   733 W gralloc4: Unable to set buffer name VRI[GameActivity]#0(BLAST Consumer)0: File name too long
12-18 14:44:31.720 12263 12294 E cutils-trace: Error opening trace file: No such file or directory (2)
12-18 14:44:31.726 12316 12316 E cutils-trace: Error opening trace file: No such file or directory (2)
12-18 14:44:31.733  1287  1466 I CHRE    : @ 410436.731: [AR] still: 40.392157
12-18 14:44:31.745 12317 12317 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstoneProto
12-18 14:44:31.748   846   846 I tombstoned: received crash request for pid 12313
12-18 14:44:31.750 12317 12317 I crash_dump64: performing dump of process 12263 (target tid = 12313)
12-18 14:44:31.796 12317 12317 E cutils-trace: Error opening trace file: No such file or directory (2)
12-18 14:44:31.810   639   639 I lowmemorykiller: Kill 'app.vanadium.browser:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:76' (11365), uid 90033, oom_score_adj 980 to free 89372kB rss, 800kB swap; reason: low watermark is breached and swap is low (208kB < 3145724kB)
12-18 14:44:31.811   639   646 E lowmemorykiller: process_mrelease 11365 failed: No such process
12-18 14:44:31.829  1458  1649 I ActivityTaskManager: Displayed org.love2d.android/.GameActivity for user 0: +699ms
12-18 14:44:31.834 12263 12263 V SDL     : onWindowFocusChanged(): true
12-18 14:44:31.836  2061  2143 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@c1c82cd
12-18 14:44:31.836  1458 13793 D CompatibilityChangeReporter: Compat change id reported: 214016041; UID 10184; state: DISABLED
12-18 14:44:31.836  1458  9787 W InputManager-JNI: Input channel object '2ff154a Splash Screen org.love2d.android (client)' was disposed without first being removed with the input manager!
12-18 14:44:31.836  1458 13793 I ImeTracker: org.love2d.android:68c1b59f: onRequestHide at ORIGIN_SERVER_HIDE_INPUT reason HIDE_UNSPECIFIED_WINDOW
12-18 14:44:31.836  1458 13793 I ImeTracker: org.love2d.android:68c1b59f: onCancelled at PHASE_SERVER_SHOULD_HIDE
12-18 14:44:31.838  1458 15851 D CoreBackPreview: Window{2ff154a u0 Splash Screen org.love2d.android EXITING}: Setting back callback null
12-18 14:44:31.844  1458 13793 I ActivityManager: Process app.vanadium.browser:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:76 (pid 11365) has died: cch+80 CACC
12-18 14:44:31.845  1458 13793 W ActivityManager: Scheduling restart of crashed service app.vanadium.browser/org.chromium.content.app.SandboxedProcessService0:76 in 13407ms for connection
12-18 14:44:31.845 29864 29864 I Zygote  : Process 11365 exited due to signal 9 (Killed)
12-18 14:44:31.846  1458  1651 D DisplayManagerService: Drop pending events for gone uid 90033
12-18 14:44:31.846  1458  1685 I libprocessgroup: Successfully killed process cgroup uid 90033 pid 11365 in 1ms
12-18 14:44:31.852  1458  1696 E system_server: Cannot read thread CPU times for PID 1458
12-18 14:44:31.983 12317 12317 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-18 14:44:31.983 12317 12317 F DEBUG   : Build fingerprint: 'google/bluejay/bluejay:14/UQ1A.231205.015/2023121200:user/release-keys'
12-18 14:44:31.983 12317 12317 F DEBUG   : Revision: 'MP1.0'
12-18 14:44:31.983 12317 12317 F DEBUG   : ABI: 'arm64'
12-18 14:44:31.983 12317 12317 F DEBUG   : Timestamp: 2023-12-18 14:44:31.756826082+0100
12-18 14:44:31.983 12317 12317 F DEBUG   : Process uptime: 2s
12-18 14:44:31.983 12317 12317 F DEBUG   : Cmdline: org.love2d.android
12-18 14:44:31.983 12317 12317 F DEBUG   : pid: 12263, tid: 12313, name: SDLThread  >>> org.love2d.android <<<
12-18 14:44:31.983 12317 12317 F DEBUG   : uid: 10184
12-18 14:44:31.983 12317 12317 F DEBUG   : tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
12-18 14:44:31.983 12317 12317 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x00005a7034f84381
12-18 14:44:31.983 12317 12317 F DEBUG   :     x0  00005a7034f84378  x1  00000000000084b8  x2  0000000000000000  x3  000000000000212e
12-18 14:44:31.983 12317 12317 F DEBUG   :     x4  0000d748f9ed30b9  x5  0000da7034f866c1  x6  0000000000000000  x7  7f7f7f7f7f7f7f7f
12-18 14:44:31.983 12317 12317 F DEBUG   :     x8  0101010101010101  x9  0000000000000000  x10 0000000000000072  x11 000000000001ffc0
12-18 14:44:31.983 12317 12317 F DEBUG   :     x12 00000000000027fa  x13 ecd71407ea82bec5  x14 0000000000000001  x15 0000092cb47728fa
12-18 14:44:31.983 12317 12317 F DEBUG   :     x16 0000d748f9fb1f58  x17 0000d748f9d355d4  x18 0000d748f3610000  x19 0000da7034f84378
12-18 14:44:31.983 12317 12317 F DEBUG   :     x20 0000d748f9d3e2a8  x21 0000d748f9fa7a50  x22 0000d748f9dec2a6  x23 0000da7034f84378
12-18 14:44:31.983 12317 12317 F DEBUG   :     x24 0000d748f3931ab8  x25 0000d748f9dec27e  x26 0000000000000001  x27 0000d748f3931abc
12-18 14:44:31.983 12317 12317 F DEBUG   :     x28 0000d748f9dec299  x29 0000d748f3931930
12-18 14:44:31.983 12317 12317 F DEBUG   :     lr  0000d748f9d461c8  sp  0000d748f3931890  pc  0000d748f9d35608  pst 0000000080001000
12-18 14:44:31.983 12317 12317 F DEBUG   : 1 total frames
12-18 14:44:31.983 12317 12317 F DEBUG   : backtrace:
12-18 14:44:31.983 12317 12317 F DEBUG   :       #00 pc 00000000004eb608  /data/app/~~j2K77F0uMKjkqVo7qw4ElA==/org.love2d.android-XqhNLd-FEKBsO5B75whpTw==/lib/arm64/liblove.so (lua_pushcclosure+52) (BuildId: 8fe929c600ae93db0f8a7c4f37948f2b49f05af9)
12-18 14:44:32.001   846   846 E tombstoned: Tombstone written to: tombstone_14
12-18 14:44:32.004  1458 12323 I DropBoxManagerService: add tag=data_app_native_crash isTagEnabled=true flags=0x2
12-18 14:44:32.006  1458 12322 W ActivityTaskManager:   Force finishing activity org.love2d.android/.GameActivity
12-18 14:44:32.007  2061  2135 V WindowManagerShell: Transition requested: android.os.BinderProxy@b3d8a4f TransitionRequestInfo { type = 2, triggerTask = null, remoteTransition = null, displayChange = null, flags = 16 }
12-18 14:44:32.028  1458  1891 I BootReceiver: Copying /data/tombstones/tombstone_14 to DropBox (SYSTEM_TOMBSTONE)
12-18 14:44:32.028  1458  1891 I DropBoxManagerService: add tag=SYSTEM_TOMBSTONE isTagEnabled=true flags=0x6
12-18 14:44:32.030  1458 13793 I ActivityManager: Process org.love2d.android (pid 12263) has died: fg  TOP 
12-18 14:44:32.031   999   999 I Zygote  : Process 12263 exited due to signal 11 (Segmentation fault)
```

**Comment by MikuAuahDark** [comment]
Could you try this debug APK? Rename the extension from .zip to .apk. Also you must uninstall existing installation of LOVE. This should hopefully provides more information about the backtrace.

[app-normal-record-debug.zip](https://github.com/love2d/love-android/files/13757807/app-normal-record-debug.zip)
