### ISSUE TITLE
11.5 Crashes on really old android

### ISSUE THREAD

**Issue by Autotren** [love2d/love-android#279]
I'm opening an issue as the official apk still lists the minimum API level to 16, and I don't know what is the intended minimum android version.
On a tablet running android 4.2.2, `love-11.5-android.apk` immediately crashes upon startup. This does not happen on 11.4.
Here's the logcat output:
```
I/ActivityManager( 2631): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.love2d.android/.GameActivity (has extras)} from pid 3085
W/GooglePlayServicesUtil( 3085): Google Play services is missing.
W/FA      ( 3085): Service connection failed: pq{statusCode=SERVICE_MISSING, resolution=null, message=null}
I/ActivityManager( 2631): Start proc org.love2d.android for activity org.love2d.android/.GameActivity: pid=6967 uid=10059 gids={50059, 1028, 1015, 3003, 3002}
I/dalvikvm( 6967): Could not find method android.os.Trace.isEnabled, referenced from method x.a.a
W/dalvikvm( 6967): VFY: unable to resolve static method 1141: Landroid/os/Trace;.isEnabled ()Z
D/dalvikvm( 6967): VFY: replacing opcode 0x71 at 0x0000
D/GameActivity( 6967): started
D/GameActivity( 6967): new gamePath:
V/SDL     ( 6967): Device: 40S404
V/SDL     ( 6967): Model: 40S404
V/SDL     ( 6967): onCreate()
D/dalvikvm( 6967): Trying to load lib /data/app-lib/org.love2d.android-1/libc++_shared.so 0x413aac88
E/dalvikvm( 6967): dlopen("/data/app-lib/org.love2d.android-1/libc++_shared.so") failed: Cannot load library: soinfo_relocate(linker.cpp:975): cannot locate symbol "statvfs" referenced by "libc++_shared.so"...
W/System.err( 6967): Cannot load library: soinfo_relocate(linker.cpp:975): cannot locate symbol "statvfs" referenced by "libc++_shared.so"...
W/dalvikvm( 6967): No implementation found for native Lorg/love2d/android/GameActivity;.nativeSetDefaultStreamValues:(II)V
D/AndroidRuntime( 6967): Shutting down VM
W/dalvikvm( 6967): threadid=1: thread exiting with uncaught exception (group=0x40fa0960)
E/AndroidRuntime( 6967): FATAL EXCEPTION: SDLActivity
E/AndroidRuntime( 6967): java.lang.UnsatisfiedLinkError: Native method not found: org.love2d.android.GameActivity.nativeSetDefaultStreamValues:(II)V
E/AndroidRuntime( 6967): 	at org.love2d.android.GameActivity.nativeSetDefaultStreamValues(Native Method)
E/AndroidRuntime( 6967): 	at org.love2d.android.GameActivity.onCreate(SourceFile)
E/AndroidRuntime( 6967): 	at android.app.Activity.performCreate(Activity.java:5104)
E/AndroidRuntime( 6967): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
E/AndroidRuntime( 6967): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
E/AndroidRuntime( 6967): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
E/AndroidRuntime( 6967): 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
E/AndroidRuntime( 6967): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
E/AndroidRuntime( 6967): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 6967): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 6967): 	at android.app.ActivityThread.main(ActivityThread.java:5041)
E/AndroidRuntime( 6967): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 6967): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 6967): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime( 6967): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
E/AndroidRuntime( 6967): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager( 2631):   Force finishing activity org.love2d.android/.GameActivity
W/GooglePlayServicesUtil( 3085): Google Play services is missing.
W/FA      ( 3085): Service connection failed: pq{statusCode=SERVICE_MISSING, resolution=null, message=null}
E/FA      ( 3085): Failed to send current screen to service
E/FA      ( 3085): Discarding data. Failed to send event to service
W/ActivityManager( 2631): Activity pause timeout for ActivityRecord{4195e008 u0 org.love2d.android/.GameActivity}
W/GooglePlayServicesUtil( 3085): Google Play services is missing.
W/FA      ( 3085): Service connection failed: pq{statusCode=SERVICE_MISSING, resolution=null, message=null}
E/FA      ( 3085): Failed to send current screen to service
I/Process ( 6967): Sending signal. PID: 6967 SIG: 9
W/InputDispatcher( 2631): channel '417d3868 org.love2d.android/org.love2d.android.GameActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher( 2631): channel '417d3868 org.love2d.android/org.love2d.android.GameActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
W/InputDispatcher( 2631): Attempted to unregister already unregistered input channel '417d3868 org.love2d.android/org.love2d.android.GameActivity (server)'
I/ActivityManager( 2631): Process org.love2d.android (pid 6967) has died.
I/WindowState( 2631): WIN DEATH: Window{417d3868 u0 org.love2d.android/org.love2d.android.GameActivity}
W/InputMethodManagerService( 2631): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@417298b0 attribute=null, token = android.os.BinderProxy@416a8350
```
For comparison, here's the output for 11.4 (which works):
```
I/ActivityManager( 2631): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.love2d.android/.GameActivity (has extras)} from pid 3085
W/GooglePlayServicesUtil( 3085): Google Play services is missing.
W/FA      ( 3085): Service connection failed: pq{statusCode=SERVICE_MISSING, resolution=null, message=null}
I/ActivityManager( 2631): Start proc org.love2d.android for activity org.love2d.android/.GameActivity: pid=6791 uid=10059 gids={50059, 1028, 1015, 3003, 3002}
W/GooglePlayServicesUtil( 3085): Google Play services is missing.
W/FA      ( 3085): Service connection failed: pq{statusCode=SERVICE_MISSING, resolution=null, message=null}
E/FA      ( 3085): Failed to send current screen to service
I/dalvikvm( 6791): Could not find method android.os.Trace.isEnabled, referenced from method i0.a.d
W/dalvikvm( 6791): VFY: unable to resolve static method 984: Landroid/os/Trace;.isEnabled ()Z
D/dalvikvm( 6791): VFY: replacing opcode 0x71 at 0x0004
E/FA      ( 3085): Discarding data. Failed to send event to service
I/dalvikvm( 6791): Could not find method android.os.Handler.createAsync, referenced from method j.b.d
W/dalvikvm( 6791): VFY: unable to resolve static method 925: Landroid/os/Handler;.createAsync (Landroid/os/Looper;)Landroid/os/Handler;
D/dalvikvm( 6791): VFY: replacing opcode 0x71 at 0x0006
I/dalvikvm( 6791): Could not find method android.app.Activity.registerActivityLifecycleCallbacks, referenced from method androidx.lifecycle.s$c.onActivityPreCreated
W/dalvikvm( 6791): VFY: unable to resolve virtual method 154: Landroid/app/Activity;.registerActivityLifecycleCallbacks (Landroid/app/Application$ActivityLifecycleCallbacks;)V
D/dalvikvm( 6791): VFY: replacing opcode 0x6e at 0x0005
D/dalvikvm( 6791): DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_ABIS
W/dalvikvm( 6791): VFY: unable to resolve static field 101 (SUPPORTED_ABIS) in Landroid/os/Build;
D/dalvikvm( 6791): VFY: replacing opcode 0x62 at 0x0024
I/dalvikvm( 6791): Could not find method android.view.View.getRootWindowInsets, referenced from method org.love2d.android.GameActivity.initializeSafeArea
W/dalvikvm( 6791): VFY: unable to resolve virtual method 1505: Landroid/view/View;.getRootWindowInsets ()Landroid/view/WindowInsets;
D/dalvikvm( 6791): VFY: replacing opcode 0x6e at 0x0012
D/dalvikvm( 6791): DexOpt: couldn't find field Landroid/view/WindowManager$LayoutParams;.layoutInDisplayCutoutMode
W/dalvikvm( 6791): VFY: unable to resolve instance field 147
D/dalvikvm( 6791): VFY: replacing opcode 0x59 at 0x0060
D/dalvikvm( 6791): DexOpt: couldn't find field Landroid/view/WindowManager$LayoutParams;.layoutInDisplayCutoutMode
W/dalvikvm( 6791): VFY: unable to resolve instance field 147
D/dalvikvm( 6791): VFY: replacing opcode 0x59 at 0x0013
I/dalvikvm( 6791): Could not find method android.view.PointerIcon.create, referenced from method org.libsdl.app.SDLActivity.createCustomCursor
W/dalvikvm( 6791): VFY: unable to resolve static method 1382: Landroid/view/PointerIcon;.create (Landroid/graphics/Bitmap;FF)Landroid/view/PointerIcon;
D/dalvikvm( 6791): VFY: replacing opcode 0x71 at 0x001b
I/dalvikvm( 6791): Could not find method android.app.Activity.checkSelfPermission, referenced from method org.libsdl.app.SDLActivity.requestPermission
W/dalvikvm( 6791): VFY: unable to resolve virtual method 88: Landroid/app/Activity;.checkSelfPermission (Ljava/lang/String;)I
D/dalvikvm( 6791): VFY: replacing opcode 0x6e at 0x0011
I/dalvikvm( 6791): Could not find method android.view.SurfaceView.setPointerIcon, referenced from method org.libsdl.app.SDLActivity.setCustomCursor
W/dalvikvm( 6791): VFY: unable to resolve virtual method 1406: Landroid/view/SurfaceView;.setPointerIcon (Landroid/view/PointerIcon;)V
D/dalvikvm( 6791): VFY: replacing opcode 0x6e at 0x0015
I/dalvikvm( 6791): Could not find method android.view.SurfaceView.setPointerIcon, referenced from method org.libsdl.app.SDLActivity.setSystemCursor
W/dalvikvm( 6791): VFY: unable to resolve virtual method 1406: Landroid/view/SurfaceView;.setPointerIcon (Landroid/view/PointerIcon;)V
D/dalvikvm( 6791): VFY: replacing opcode 0x6e at 0x0035
I/dalvikvm( 6791): Could not find method android.content.res.Configuration.getLocales, referenced from method org.libsdl.app.SDLActivity.startNative
W/dalvikvm( 6791): VFY: unable to resolve virtual method 442: Landroid/content/res/Configuration;.getLocales ()Landroid/os/LocaleList;
D/dalvikvm( 6791): VFY: replacing opcode 0x6e at 0x0063
D/GameActivity( 6791): started
D/GameActivity( 6791): new gamePath:
V/SDL     ( 6791): Device: 40S404
V/SDL     ( 6791): Model: 40S404
V/SDL     ( 6791): onCreate()
D/dalvikvm( 6791): Trying to load lib /data/app-lib/org.love2d.android-1/libc++_shared.so 0x413a8f10
D/dalvikvm( 6791): Added shared lib /data/app-lib/org.love2d.android-1/libc++_shared.so 0x413a8f10
D/dalvikvm( 6791): No JNI_OnLoad found in /data/app-lib/org.love2d.android-1/libc++_shared.so 0x413a8f10, skipping init
D/dalvikvm( 6791): Trying to load lib /data/app-lib/org.love2d.android-1/libmpg123.so 0x413a8f10
D/dalvikvm( 6791): Added shared lib /data/app-lib/org.love2d.android-1/libmpg123.so 0x413a8f10
D/dalvikvm( 6791): No JNI_OnLoad found in /data/app-lib/org.love2d.android-1/libmpg123.so 0x413a8f10, skipping init
D/dalvikvm( 6791): Trying to load lib /data/app-lib/org.love2d.android-1/libopenal.so 0x413a8f10
D/dalvikvm( 6791): Added shared lib /data/app-lib/org.love2d.android-1/libopenal.so 0x413a8f10
D/dalvikvm( 6791): No JNI_OnLoad found in /data/app-lib/org.love2d.android-1/libopenal.so 0x413a8f10, skipping init
D/dalvikvm( 6791): Trying to load lib /data/app-lib/org.love2d.android-1/liblove.so 0x413a8f10
D/dalvikvm( 6791): Added shared lib /data/app-lib/org.love2d.android-1/liblove.so 0x413a8f10
V/SDL     ( 6791): nativeSetupJNI()
I/dalvikvm( 6791): Could not find method android.media.AudioTrack.write, referenced from method org.libsdl.app.SDLAudioManager.audioWriteFloatBuffer
W/dalvikvm( 6791): VFY: unable to resolve virtual method 864: Landroid/media/AudioTrack;.write ([FIII)I
D/dalvikvm( 6791): VFY: replacing opcode 0x6e at 0x0015
I/dalvikvm( 6791): Could not find method android.media.AudioRecord.read, referenced from method org.libsdl.app.SDLAudioManager.captureReadByteBuffer
W/dalvikvm( 6791): VFY: unable to resolve virtual method 847: Landroid/media/AudioRecord;.read ([BIII)I
D/dalvikvm( 6791): VFY: replacing opcode 0x6e at 0x0014
I/dalvikvm( 6791): Could not find method android.media.AudioRecord.read, referenced from method org.libsdl.app.SDLAudioManager.captureReadFloatBuffer
W/dalvikvm( 6791): VFY: unable to resolve virtual method 848: Landroid/media/AudioRecord;.read ([FIII)I
D/dalvikvm( 6791): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm( 6791): Could not find method android.media.AudioRecord.read, referenced from method org.libsdl.app.SDLAudioManager.captureReadShortBuffer
W/dalvikvm( 6791): VFY: unable to resolve virtual method 850: Landroid/media/AudioRecord;.read ([SIII)I
D/dalvikvm( 6791): VFY: replacing opcode 0x6e at 0x0014
V/SDL     ( 6791): AUDIO nativeSetupJNI()
V/SDL     ( 6791): CONTROLLER nativeSetupJNI()
E/dalvikvm( 6791): Could not find class 'android.bluetooth.BluetoothManager', referenced from method org.libsdl.app.HIDDeviceManager.initializeBluetooth
W/dalvikvm( 6791): VFY: unable to resolve check-cast 54 (Landroid/bluetooth/BluetoothManager;) in Lorg/libsdl/app/HIDDeviceManager;
D/dalvikvm( 6791): VFY: replacing opcode 0x1f at 0x0042
I/dalvikvm( 6791): Could not find method android.bluetooth.BluetoothManager.getConnectedDevices, referenced from method org.libsdl.app.HIDDeviceManager.chromebookConnectionHandler
W/dalvikvm( 6791): VFY: unable to resolve virtual method 292: Landroid/bluetooth/BluetoothManager;.getConnectedDevices (I)Ljava/util/List;
D/dalvikvm( 6791): VFY: replacing opcode 0x6e at 0x0012
W/dalvikvm( 6791): Unable to resolve superclass of Lorg/libsdl/app/HIDDeviceBLESteamController; (50)
W/dalvikvm( 6791): Link of class 'Lorg/libsdl/app/HIDDeviceBLESteamController;' failed
E/dalvikvm( 6791): Could not find class 'org.libsdl.app.HIDDeviceBLESteamController', referenced from method org.libsdl.app.HIDDeviceManager.connectBluetoothDevice
W/dalvikvm( 6791): VFY: unable to resolve check-cast 1424 (Lorg/libsdl/app/HIDDeviceBLESteamController;) in Lorg/libsdl/app/HIDDeviceManager;
D/dalvikvm( 6791): VFY: replacing opcode 0x1f at 0x0040
W/dalvikvm( 6791): Unable to resolve superclass of Lorg/libsdl/app/HIDDeviceBLESteamController; (50)
W/dalvikvm( 6791): Link of class 'Lorg/libsdl/app/HIDDeviceBLESteamController;' failed
E/dalvikvm( 6791): Could not find class 'org.libsdl.app.HIDDeviceBLESteamController', referenced from method org.libsdl.app.HIDDeviceManager.connectBluetoothDevice
W/dalvikvm( 6791): VFY: unable to resolve new-instance 1424 (Lorg/libsdl/app/HIDDeviceBLESteamController;) in Lorg/libsdl/app/HIDDeviceManager;
D/dalvikvm( 6791): VFY: replacing opcode 0x22 at 0x0048
W/dalvikvm( 6791): Unable to resolve superclass of Lorg/libsdl/app/HIDDeviceBLESteamController; (50)
W/dalvikvm( 6791): Link of class 'Lorg/libsdl/app/HIDDeviceBLESteamController;' failed
E/dalvikvm( 6791): Could not find class 'org.libsdl.app.HIDDeviceBLESteamController', referenced from method org.libsdl.app.HIDDeviceManager.disconnectBluetoothDevice
W/dalvikvm( 6791): VFY: unable to resolve check-cast 1424 (Lorg/libsdl/app/HIDDeviceBLESteamController;) in Lorg/libsdl/app/HIDDeviceManager;
D/dalvikvm( 6791): VFY: replacing opcode 0x1f at 0x0007
I/dalvikvm( 6791): Could not find method android.bluetooth.BluetoothDevice.getType, referenced from method org.libsdl.app.HIDDeviceManager.isSteamController
W/dalvikvm( 6791): VFY: unable to resolve virtual method 269: Landroid/bluetooth/BluetoothDevice;.getType ()I
D/dalvikvm( 6791): VFY: replacing opcode 0x6e at 0x0017
W/dalvikvm( 6791): Unable to resolve superclass of Lorg/libsdl/app/HIDDeviceBLESteamController; (50)
W/dalvikvm( 6791): Link of class 'Lorg/libsdl/app/HIDDeviceBLESteamController;' failed
D/dalvikvm( 6791): DexOpt: unable to opt direct call 0x259b at 0x4a in Lorg/libsdl/app/HIDDeviceManager;.connectBluetoothDevice
I/dalvikvm( 6791): Could not find method android.app.Activity.isInMultiWindowMode, referenced from method org.libsdl.app.SDLSurface.surfaceChanged
W/dalvikvm( 6791): VFY: unable to resolve virtual method 123: Landroid/app/Activity;.isInMultiWindowMode ()Z
D/dalvikvm( 6791): VFY: replacing opcode 0x6e at 0x00db
V/SDL     ( 6791): onStart()
V/SDL     ( 6791): onResume()
D/libEGL  ( 6791): loaded /system/lib/egl/libEGL_VIVANTE.so
D/libEGL  ( 6791): loaded /system/lib/egl/libGLESv1_CM_VIVANTE.so
D/libEGL  ( 6791): loaded /system/lib/egl/libGLESv2_VIVANTE.so
E/BufferQueue( 2108): [org.love2d.android/org.love2d.android.GameActivity] dequeueBuffer: can't dequeue multiple buffers without setting the buffer count
D/OpenGLRenderer( 6791): Enabling debug mode 0
V/SDL     ( 6791): surfaceCreated()
V/SDL     ( 6791): surfaceChanged()
V/SDL     ( 6791): Window size: 1024x720
V/SDL     ( 6791): Device size: 1024x768
V/SDL     ( 6791): Running main function SDL_main from library /data/app-lib/org.love2d.android-1/liblove.so
V/SDL     ( 6791): nativeRunMain()
D/GameActivity( 6791): called getGamePath(), game path =
D/GameActivity( 6791): fallback to lovegame folder
D/GameActivity( 6791): lovegame directory:
I/SDL/APP ( 6791): Mounting  did not work. Loading to memory.
I/SDL/APP ( 6791): Could not find
I/SDL/APP ( 6791): Failure memory loading archive
V/SDL     ( 6791): onWindowFocusChanged(): true
I/ActivityManager( 2631): Displayed org.love2d.android/.GameActivity: +483ms
V/SDL     ( 6791): setOrientation() requestedOrientation=10 width=800 height=600 resizable=true hint=
V/SDL     ( 6791): setOrientation() requestedOrientation=10 width=800 height=600 resizable=true hint=
E/BufferQueue( 2108): [SurfaceView] dequeueBuffer: can't dequeue multiple buffers without setting the buffer count
I/SDL/APP ( 6791): pixel format wanted SDL_PIXELFORMAT_RGBA8888 (1), got SDL_PIXELFORMAT_RGBA8888 (1)
V/SDL     ( 6791): setOrientation() requestedOrientation=10 width=800 height=600 resizable=true hint=
V/SDL     ( 6791): setOrientation() requestedOrientation=10 width=800 height=600 resizable=true hint=
I/SDL/APP ( 6791): pixel format wanted SDL_PIXELFORMAT_RGBA8888 (1), got SDL_PIXELFORMAT_RGBA8888 (1)
W/ThrottleService( 2631): unable to find stats for iface rmnet0
```

**Comment by MikuAuahDark** [comment]
Looks like by updating NDK to r24 we effectively removed support for Jelly Bean and lower. See android/ndk#1727.

Unfortunately it's one of case where we need to trade-off between supporting newer Android device (older NDK doesn't support newer Android device) or keeping support for those ancient OSes (newer NDK doesn't support older devices).

Thanks for making aware of this. I'll bump the min SDK version to 18.
